    steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/oracle-329410/jaastest', '.' ]
    options:
      logging: CLOUD_LOGGING_ONLY
    images: [gcr.io/oracle-329410/jaastest:latest]